server:
  port: 9089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sgcc?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: amproot
    password: amproot
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: sgcc
      uri: mongodb://localhost:27017/sgcc
  servlet:
    multipart:
      maxFileSize: 300MB
      maxRequestSize: 1000MB

  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  application:
    name: file_service

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.sgcc.zj.bean
  mapperLocations: classpath:mapper/*.xml

upload:
  uploadPathName: D:/upload/file/ #上传存储本地文件的位置

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/